[package]
name = "block-place"
version = "0.1.0"
authors = ["Amber Kowalski <amberkowalski03@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
