[workspace]
members = [
    "api",

    "core",
    "core/anvil",
    "core/blocks",
    "core/blocks/generator",
    "core/biomes",
    "core/chunk",
    "core/chunk_map",
    "core/entity_metadata",
    "core/item_block",
    "core/items",
    "core/loot",
    "core/loot/model",
    "core/misc",
    "core/inventory",
    "core/network",
    "core/text",
    "core/util",

    "definitions",
    "definitions/generator",

    "server",
    "server/template",
    "server/block",
    "server/chat",
    "server/chunk",
    "server/commands",
    "server/config",
    "server/entity",
    "server/lighting",
    "server/network",
    "server/packet_buffer",
    "server/physics",
    "server/player",
    "server/test",
    "server/types",
    "server/util",
    "server/weather",
    "server/worldgen",

    "codegen",
    "data",
    "data/macro"
]

# To make sure the server isn't dirt slow in debug mode.
[profile.dev]
opt-level = 1
