[workspace]
members = [
    # Listed in the order they appear in the dependency tree (from bottom to top)
    "crates/utils",
    "crates/generated",
    "crates/blocks",
    "crates/blocks/generator",
    "crates/base",
    "crates/ecs",
    "crates/datapacks",
    "crates/worldgen",
    "crates/common",
    "crates/protocol",
    "crates/server",

    "tools/proxy",
]

# Temp until we finish porting everything to new 1.16 design
exclude = [
    "core",
    "core/anvil",
    "core/blocks",
    "core/blocks/generator",
    "core/biomes",
    "core/chunk",
    "core/chunk_map",
    "core/entity_metadata",
    "core/item_block",
    "core/items",
    "core/loot",
    "core/loot/model",
    "core/misc",
    "core/protocol",
    "core/inventory",
    "core/text",
    "core/util",

    "definitions",
    "definitions/generator",

    "server",
    "server/template",
    "server/block",
    "server/chat",
    "server/chunk",
    "server/commands",
    "server/config",
    "server/entity",
    "server/lighting",
    "server/network",
    "server/packet_buffer",
    "server/physics",
    "server/player",
    "server/test",
    "server/types",
    "server/util",
    "server/weather",
    "server/worldgen",

    "data",
    "data/macro"
]
