[package]
name = "feather-commands"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]

commands = { git = "https://github.com/Iaiao/commands", rev = "2d46d6807c9758b0b17182a2ecdcc8c1d476004d" }
smallvec = "1.4"
anyhow = "1.0"
rand = "0.7"
vek = "0.10"
uuid = { version = "0.8", features = [ "v3" ] }
tokio = { version = "0.2", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }
log = "0.4.14"
common = { path = "../common", package = "feather-common" }
ecs = { path = "../ecs", package = "feather-ecs" }
quill-common = { path = "../../quill/common" }
libcraft-text = { path = "../../libcraft/text" }
libcraft-items = { path = "../../libcraft/items" }
libcraft-core = { path = "../../libcraft/core" }
feather-datapacks = { path = "../datapacks" }
