[package]
name = "feather-base"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
ahash = "0.4"
anyhow = "1"
arrayvec = { version = "0.7", features = [ "serde" ] }
bitflags = "1"
bitvec = "0.21"
bytemuck = { version = "1", features = ["derive"] }
byteorder = "1"
derive_more = "0.99"
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt" }
indexmap = "1"
itertools = "0.10"
konst = "0.2"
libcraft-blocks = { path = "../../libcraft/blocks" }
libcraft-core = { path = "../../libcraft/core" }
libcraft-inventory = { path = "../../libcraft/inventory" } 
libcraft-items = { path = "../../libcraft/items" }
libcraft-particles = { path = "../../libcraft/particles" }
libcraft-text = { path = "../../libcraft/text" }
nom = "5"
nom_locate = "2"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1"
parking_lot = "0.11"
quill = { path = "../../quill" }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_with = "1"
smallvec = "1"
thiserror = "1"
uuid = { version = "0.8", features = [ "serde" ] }
vek = "0.14"

[dev-dependencies]
rand = "0.8"
rand_pcg = "0.3"
serde_test = "1"
