[package]
name = "feather_codegen"
version = "0.2.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.43", features = ["full", "extra-traits", "derive"] }
quote = "0.6.13"
proc-macro2 = "0.4.30"
lazy_static = "1.3.0"
heck = "0.3.1"