[package]
name = "quill-ecs"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
ahash = "0.7"
arrayvec = "0.5"
itertools = "0.10"
once_cell = "1"
thiserror = "1"
thread_local= "1"
