[package]
name = "feather_server"
version = "0.3.0"
authors = ["caelunshun <caelum12321@gmail.com>"]
edition = "2018"

[dependencies]
feather_core = { path = "../core" }
feather_blocks = { path = "../blocks/lib" }
mio = "0.6.19"
mio-extras = { git = "https://github.com/caelunshun/mio-extras", rev = "e5dca5d" }
crossbeam = "0.7.1"
log = "0.4.6"
simple_logger = "1.3.0"
uuid = { version = "0.7.4", features = ["v4"] }
derive-new = "0.5.6"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
toml = "0.5.1"
openssl = { version = "0.10.23", features = ["vendored"] }
rand = "0.7.0"
bytes = "0.4.12"
hashbrown = "0.5.0"
mojang-api = "0.1.0"
multimap = "0.5.0"
rnbt = { git = "https://github.com/caelunshun/rnbt", version = "0.1.0" }
specs = "0.15.0"

[dev-dependencies]
mockers = "0.21.0"
mockers_derive = "0.21.0"
