[package]
name = "feather-server"
version = "0.4.1"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-blocks = { path = "../blocks" }
feather-core = { path = "../core" }
feather-item-block = { path = "../item_block" }
mio = "0.6.19"
mio-extras = "2.0.5"
crossbeam = "0.7.2"
log = "0.4.8"
simple_logger = "1.3.0"
uuid = { version = "0.7.4", features = ["v4"] }
derive-new = "0.5.8"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
toml = "0.5.3"
rsa = "0.1.3"
rsa-der = "0.2.1"
rand = "0.7.0"
rand-legacy = { path = "../util/rand-legacy" }
bytes = "0.4.12"
hashbrown = { version = "0.6.0", features = ["rayon"] }
mojang-api = "0.1.2"
multimap = "0.6.0"
hematite-nbt = "0.4.1"

#The storage-event-control feature is not in a stable version yet,
#thus we need to use the git version.
#Should be changed once the feature is in a stable version
specs = { git = "https://github.com/slide-rs/specs", features = ["storage-event-control"] }

rayon = "1.1.2"
shrev = "1.1.1"
failure = "0.1.5"
backtrace = "0.3.35"
num-derive = "0.2.5"
num-traits = "0.2.8"
smallvec = "0.6.10"
lazy_static = "1.4.0"
nalgebra-glm = "0.4.2"
nalgebra = "0.18.1"
ncollide3d = "0.20.1"
derive_deref = "1.1.0"
feather-codegen = { path = "../codegen" }
bitflags = "1.1.0"
fnv = "1.0.6"
base64 = "0.10.1"
bumpalo = "2.6.0"
thread_local = "0.3.6"
parking_lot = "0.9.0"
heapless = "0.5.1"

[features]
nightly = ["specs/nightly", "parking_lot/nightly"]
