[package]
name = "feather-worldgen"
version = "0.6.0"
authors = [ "caelunshun <caelunshun@gmail.com>" ]
edition = "2018"

[dependencies]
base = { path = "../base", package = "feather-base" }
log = "0.4.14"
