[package]
name = "minecraft-proxy"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-protocol = { path = "../../feather/protocol", features = ["proxy"] }
async-executor = "1"
async-io = "1"
futures-lite = "1"
argh = "0.1"
anyhow = "1"
log = "0.4"
simple_logger = "1"
either = "1"
