[package]
name = "feather-common"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
base = { path = "../base", package = "feather-base" }
generated = { path = "../generated", package = "feather-generated" }
ecs = { path = "../ecs", package = "feather-ecs" }
utils = { path = "../utils", package = "feather-utils" }
blocks = { path = "../blocks", package = "feather-blocks" }

smartstring = "0.2"
uuid = { version = "0.8", features = ["v4"] }
log = "0.4"
itertools = "0.10"
anyhow = "1"
ahash = "0.7"
parking_lot = "0.11"
flume = "0.10"
quill-common = { path = "/home/caelum/dev/quill/crates/quill-common" }
