[package]
name = "libcraft-core"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
strum = "0.21"
strum_macros = "0.21"
vek = "0.14"