[package]
name = "feather-common"
version = "0.1.0"
authors = [ "caelunshun <caelunshun@gmail.com>" ]
edition = "2018"

[dependencies]
ahash = "0.7"
anyhow = "1"
base = { path = "../base", package = "feather-base" }
flume = "0.10"
itertools = "0.10"
log = "0.4"
parking_lot = "0.11"
quill-common = { path = "../../quill/common" }
smartstring = "0.2"
utils = { path = "../utils", package = "feather-utils" }
uuid = { version = "0.8", features = [ "v4" ] }
libcraft-core = { path = "../../libcraft/core" }
libcraft-inventory = { path = "../../libcraft/inventory" }
libcraft-items = { path = "../../libcraft/items" }
libcraft-blocks = { path = "../../libcraft/blocks" }
rayon = "1.5"
worldgen = { path = "../worldgen", package = "feather-worldgen" }
rand = "0.8"
derive_more = "0.99"
vane = { path = "../../vane" }
