[package]
name = "feather-server"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"
default-run = "feather-server"

[[bin]]
path = "src/main.rs"
name = "feather-server"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common", package = "feather-common" }
base = { path = "../base", package = "feather-base" }
ecs = { path = "../ecs", package = "feather-ecs" }
protocol = { path = "../protocol", package = "feather-protocol" }
utils = { path = "../utils", package = "feather-utils" }
plugin-host = { path = "../plugin-host", package = "feather-plugin-host" }

ahash = "0.7"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
flume = "0.10"
futures-lite = "1"
base64 = "0.13"
log = "0.4"
fern = "0.6"
colored = "2"
chrono = "0.4"
ureq = { version = "2", features = ["json"] }
rsa = "0.3"
rsa-der = "0.2"
once_cell = "1"
sha-1 = "0.9"
md-5 = "0.9"
rand = "0.7"
num-bigint = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = "0.8"
vec-arena = "1"
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt" }
parking_lot = "0.11"
quill-common = { path = "/home/caelum/dev/quill/crates/quill-common" }

[features]
default = ["plugin-cranelift"]

# Use Cranelift to JIT-compile plugins. Pure Rust
# but produces slower code than LLVM.
plugin-cranelift = ["plugin-host/cranelift"]
# Use LLVM to JIT-compile plugins. Produces
# very fast code, but requires LLVM to be installed
# on the build system. May impact startup times.
plugin-llvm = ["plugin-host/llvm"]
