name: build

on:
  push:
    branches: [ develop, master, staging ]
  pull_request:
    branches: [ develop, master, staging ]

jobs:
  build:
    name: "Build and Test"
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # Caching
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry3-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry3-
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index3-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index3-
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target3-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-target3-

    - name: Install rustfmt
      run: rustup component add rustfmt
      
    - name: Run tests
      run: cargo test
      env:
        RUSTFLAGS: "-C opt-level=0 -C debuginfo=0"

    - name: Install Clippy
      run: rustup component add clippy
    
    - name: Run Clippy
      run: cargo clippy --all-targets -- -D warnings
      env:
        RUSTFLAGS: "-C opt-level=0 -C debuginfo=0"
    
    - name: Check formatting
      run: cargo fmt -- --check
